routing:

# Front office [anonymous, user, admin]
    home: # Page d'accueil
        path: /
        controller: HomeController/index
        roles: [anonymous, user, admin]
    login: # Page de connexion
        path: /login
        controller: SecurityController/login
        roles: [anonymous, user, admin]
    logout: # Page de déconnexion
        path: /logout
        controller: SecurityController/logout
        roles: [anonymous, user, admin]
    register: # Page des création de comte
        path: /register
        controller: SecurityController/register
        roles: [anonymous, user, admin]
    forgotPassword:
        path: /forgotPassword
        controller: SecurityController/forgotPassword
        roles: [anonymous, user, admin]
    posts: # liste des articles publiée
        path: /posts
        controller: PostController/index
        roles: [anonymous, user, admin]
    post: # page d'un article 
        path: /post/{id}
        controller: PostController/post
        roles: [anonymous, user, admin]
    user: # affiche l'utilisateur
        path: /user/{id}
        controller: UserController/user
        roles: [anonymous, user, admin]
    error_404:
        path: /404
        controller: ErrorController/error404
        roles: [anonymous, user, admin]
# ----------------------------------------------#
# ------------ global users routes ------------ #
# ----------------------------------------------#

# Front office [users, admin]
    edit_user: # modifie l'utilisateur courrant
        path: /user/edit/{id}
        controller: UserController/editUser
        roles: [user, admin]
    edit_user_data: 
        path: /user/edit/data/{id}
        controller: UserController/editUserData
        roles: [user, admin]
    edit_user_profilePicture:
        path: /user/edit/profilePicture/{id}
        controller: UserController/editUserProfilePicture
        roles: [user, admin]
    edit_user_password:
        path: /user/edit/password/{id}
        controller: UserController/editUserPassword
        roles: [user, admin]

# ----------------------------------------------#
# ------------ global users posts ------------- #
# ----------------------------------------------#

    posts_user: # liste les articles de l'utilisateur courrant
        path: /user/posts/{id}
        controller: PostController/userPosts
        roles: [user, admin]
    edit_post_user:
        path: /user/post/edit/{id}
        controller: PostController/userEditPost
        roles: [user, admin]
    new_post_user:
        path: /user/post/new
        controller: PostController/userNewPost
        roles: [user, admin]

# ----------------------------------------------#
# ---------- global users comments ------------ #
# ----------------------------------------------#
    new_comment: # créer un commentaire
        path: /user/comment/new
        controller: CommentController/newComment
        roles: [user, admin]

# ----------------------------------------------#
# ----------- global users divers ------------- #
# ----------------------------------------------#
    follow_user:
        path: /user/follow/{id}
        controller: UserController/followUser
        roles: [user, admin]

    upload_image: # ajoute une image a l'article
        path: /user/post/upload/
        controller: PostController/uploadImage
        roles: [admin, user]

# ----------------------------------------------#
# ------------------- ADMIN ------------------- #
# ----------------------------------------------#
# Admin office [admin]
    admin: 
        path: /admin
        controller: AdminController/admin
        roles: [admin]

# ----------------------------------------------#
# -------------- global admin users ----------- #
# ----------------------------------------------#
    users_admin:
        path: /admin/users
        controller: AdminController/usersAdmin
        roles: [admin]
    user_admin:
        path: /admin/user/{id}
        controller: AdminController/userAdmin
        roles: [admin]
    edit_admin_user:
        path: /admin/user/edit/{id}
        controller: AdminController/editUserAdmin
        roles: [admin]
    remove_admin_user:
        path: /admin/user/remove/{id}
        controller: AdminController/removeUserAdmin
        roles: [admin]

# ----------------------------------------------#
# ---------- global admin comments ------------ #
# ----------------------------------------------#
    comments_admin:
        path: /admin/comments
        controller: AdminController/commentsAdmin
        roles: [admin]
    comment_toggle_status:
        path: /admin/comment/toggleStatus/{id}
        controller: CommentController/toggleStatus
        roles: [admin]
    comment_remove:
        path: /admin/comment/remove/{id}
        controller: CommentController/removeComment
        roles: [admin]

# ----------------------------------------------#
# ------------ global admin posts ------------- #
# ----------------------------------------------#
    posts_admin:
        path: /admin/posts
        controller: AdminController/postsAdmin
        roles: [admin]
    post_toggle_status:
        path: /admin/post/toggleStatus/{id}
        controller: AdminController/adminToggleStatus
        roles: [admin]
    admin_new_post: # création d'un nouvelle article
        path: /admin/post/new
        controller: AdminController/adminNewPost
        roles: [admin]
    admin_edit_post: # modification d'un article
        path: /admin/post/edit/{id}
        controller: AdminController/adminEditPost
        roles: [admin]
    edit_user_admin:
        path: /admin/user/edit/{id}
        controller: AdminController/userEdit
        roles: [admin]
